=== atantri/resfinder/target/classes/java/dataXmls/AddRestaurantRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/AddRestaurantRequestFinder" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
<element name="AddRestaurantRequestList">
	<complexType>
		<sequence>
			<element name="AddRestaurantRequest" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Id" minOccurs="1" maxOccurs="1" type="integer"></element>
					  	<element name="ManagerId" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="RestaurantName" minOccurs="1" maxOccurs="1" type="string"></element>
						<element name="CuisineString" minOccurs="1" maxOccurs="1" type="string"></element>
						<element name="Address" minOccurs="1" maxOccurs="1" type="string"></element>
						<element name="Status" minOccurs="1" maxOccurs="1" type="string"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== atantri/resfinder/target/classes/java/dataXmls/AddRestaurantRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<AddRestaurantRequestList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/AddRestaurantRequestFinder" xsi:noNamespaceSchemaLocation="AddRestaurantRequest.xsd">
	<AddRestaurantRequest>
		<Id>1</Id>
		<ManagerId>1</ManagerId>
		<RestaurantName>KFC</RestaurantName>
		<CuisineString>Fast Food</CuisineString>
		<Address>711 Bethel Rd, Columbus, OH</Address>
		<Status>PENDING</Status>
	</AddRestaurantRequest>	
</AddRestaurantRequestList>
