=== atantri/resfinder/target/classes/java/dataXmls/UserLocationMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/UserLocationMapFinder" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
<element name="UserLocationMapList">
	<complexType>
		<sequence>
			<element name="UserLocationMap" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Id" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="UserId" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="LocationId" minOccurs="1" maxOccurs="1" type="integer"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== atantri/resfinder/target/classes/java/dataXmls/UserLocationMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<UserLocationMapList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/UserLocationMapFinder" xsi:noNamespaceSchemaLocation="UserLocationMap.xsd">
 	<UserLocationMap>
 		<Id>1</Id>
		<UserId>1</UserId>
		<LocationId>2</LocationId>
 	</UserLocationMap>
 	<UserLocationMap>
 		<Id>2</Id>
		<UserId>2</UserId>
		<LocationId>1</LocationId>
 	</UserLocationMap>
</UserLocationMapList>
