=== atantri/resfinder/target/classes/java/dataXmls/UserCuisineMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/UserCuisineMapFinder" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
<element name="UserCuisineMapList">
	<complexType>
		<sequence>
			<element name="UserCuisineMap" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Id" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="UserId" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="CuisineId" minOccurs="1" maxOccurs="1" type="integer"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== atantri/resfinder/target/classes/java/dataXmls/UserCuisineMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<UserCuisineMapList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/UserCuisineMapFinder" xsi:noNamespaceSchemaLocation="UserCuisineMap.xsd">
 	<UserCuisineMap>
 		<Id>1</Id>
		<UserId>1</UserId>
		<CuisineId>2</CuisineId>
 	</UserCuisineMap> 	
 	<UserCuisineMap>
 		<Id>2</Id>
		<UserId>2</UserId>
		<CuisineId>1</CuisineId>
 	</UserCuisineMap>
</UserCuisineMapList>
