=== atantri/resfinder/src/main/java/dataXmls/Cuisine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/CuisineFinder" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
<element name="CuisineList">
	<complexType>
		<sequence>
			<element name="Cuisine" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Id" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="Name" minOccurs="1" maxOccurs="1" type="string"></element>
						<element name="Description" minOccurs="1" maxOccurs="1" type="string"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== atantri/resfinder/target/classes/java/dataXmls/Cuisine.xml
<?xml version="1.0" encoding="UTF-8"?>
<CuisineList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/CuisineFinder" xsi:noNamespaceSchemaLocation="Cuisine.xsd">
	<Cuisine>
		<Id>1</Id>
		<Name> French </Name>
		<Description> Salade ni√ßoise, Bouillabaisse, Ratatouille, Seafood </Description>
	</Cuisine>	
	<Cuisine>
		<Id>2</Id>
		<Name> Southern </Name>
		<Description> Fried Chicken, Coleslaw, Cheese Fries </Description>
	</Cuisine>
</CuisineList>
