=== atantri/resfinder/src/main/java/dataXmls/Recommendation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/RecommendationFinder" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
<element name="RecommendationList">
	<complexType>
		<sequence>
			<element name="Recommendation" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Id" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="UserId" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="RestaurantId" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="DateAdded" minOccurs="1" maxOccurs="1" type="dateTime"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== atantri/resfinder/target/classes/java/dataXmls/Recommendation.xml
<?xml version="1.0" encoding="UTF-8"?>
<RecommendationList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/RecommendationFinder" xsi:noNamespaceSchemaLocation="Recommendation.xsd">
	<Recommendation>
		<Id>1</Id>
		<UserId>1</UserId>
		<RestaurantId>2</RestaurantId>
		<DateAdded> 2013-09-19T20:32:52 </DateAdded>
	</Recommendation>	
	<Recommendation>
		<Id>2</Id>
		<UserId>2</UserId>
		<RestaurantId>1</RestaurantId>
		<DateAdded> 2013-09-19T22:32:52 </DateAdded>
	</Recommendation>
</RecommendationList>
