=== atantri/resfinder/src/main/java/dataXmls/Restaurant.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/RestaurantFinder" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">
<element name="RestaurantList">
	<complexType>
		<sequence>
			<element name="Restaurant" minOccurs="1" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="Id" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="Name" minOccurs="1" maxOccurs="1" type="string"></element>
						<element name="Rating" minOccurs="1" maxOccurs="1" type="integer"></element>
						<element name="Address" minOccurs="1" maxOccurs="1" type="string"></element>
						<element name="LocationId" minOccurs="1" maxOccurs="1" type="integer"></element>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== atantri/resfinder/target/classes/java/dataXmls/Restaurant.xml
<?xml version="1.0" encoding="UTF-8"?>
<RestaurantList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.org/RestaurantFinder" xsi:noNamespaceSchemaLocation="Restaurant.xsd">
	<Restaurant>
		<Id>1</Id>
		<Name>KFC</Name>
		<Rating>3</Rating>
		<Address>711 Bethel Rd, Columbus, OH </Address>
		<LocationId>1</LocationId>
	</Restaurant>	
	<Restaurant>
		<Id>2</Id>
		<Name>McDonald's</Name>
		<Rating>4</Rating>
		<Address>910 W 5th Ave, Columbus, OHâ€Ž</Address>
		<LocationId>2</LocationId>
	</Restaurant>	
</RestaurantList>
